-- IP池基础信息管理模块迁移脚本
-- 执行前请先备份数据库

-- 1) 扩展 ip_pool
ALTER TABLE ip_pool
  ADD COLUMN IF NOT EXISTS region VARCHAR(50) NULL COMMENT '网络区域',
  ADD COLUMN IF NOT EXISTS network_type VARCHAR(10) NOT NULL DEFAULT 'IPv4' COMMENT 'IPv4/IPv6',
  ADD COLUMN IF NOT EXISTS start_ip VARCHAR(64) NULL COMMENT '起始IP',
  ADD COLUMN IF NOT EXISTS end_ip VARCHAR(64) NULL COMMENT '结束IP',
  ADD COLUMN IF NOT EXISTS subnet_mask VARCHAR(64) NULL COMMENT '子网掩码/前缀',
  ADD COLUMN IF NOT EXISTS gateway VARCHAR(64) NULL COMMENT '网关',
  ADD COLUMN IF NOT EXISTS dns VARCHAR(255) NULL COMMENT 'DNS列表(逗号分隔)',
  ADD COLUMN IF NOT EXISTS lease_hours INT NULL COMMENT '租期(小时)',
  ADD COLUMN IF NOT EXISTS enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用';

-- 2) 扩展 ip_registry（静态绑定）
ALTER TABLE ip_registry
  ADD COLUMN IF NOT EXISTS device_name VARCHAR(100) NULL COMMENT '设备名称',
  ADD COLUMN IF NOT EXISTS department VARCHAR(100) NULL COMMENT '部门',
  ADD COLUMN IF NOT EXISTS owner VARCHAR(100) NULL COMMENT '负责人',
  ADD COLUMN IF NOT EXISTS purpose VARCHAR(255) NULL COMMENT '用途',
  ADD COLUMN IF NOT EXISTS is_bound TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否绑定',
  ADD COLUMN IF NOT EXISTS bound_at DATETIME NULL COMMENT '绑定时间',
  ADD COLUMN IF NOT EXISTS unbound_at DATETIME NULL COMMENT '解绑时间';

CREATE INDEX IF NOT EXISTS idx_ip_registry_pool_ip_bound ON ip_registry(pool_id, ip, is_bound);
